# Generated by Django 4.2.11 on 2026-04-06 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('PR', 'Purchase Requisition'), ('PO', 'Purchase Order')], db_column='entity_type', max_length=10)),
                ('min_amount', models.DecimalField(db_column='min_amount', decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, db_column='max_amount', decimal_places=2, max_digits=15, null=True)),
                ('approver_role', models.CharField(db_column='approver_role', max_length=100)),
            ],
            options={
                'db_table': 'approval_workflows',
                'ordering': ['entity_type', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grn_number', models.CharField(blank=True, db_column='grn_number', max_length=50, unique=True)),
                ('received_date', models.DateField(db_column='received_date', default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Inspected', 'QC Inspected')], db_column='status', default='Draft', max_length=20)),
            ],
            options={
                'db_table': 'goods_receipts',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_name', models.CharField(db_column='term_name', max_length=100)),
                ('days', models.IntegerField(db_column='days', default=0)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
            ],
            options={
                'db_table': 'payment_terms',
                'ordering': ['days'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(blank=True, db_column='po_number', max_length=50, unique=True)),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now)),
                ('expected_delivery', models.DateField(blank=True, db_column='expected_delivery', null=True)),
                ('currency', models.CharField(db_column='currency', default='PKR', max_length=10)),
                ('total_amount', models.DecimalField(db_column='total_amount', decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Sent', 'Sent to Supplier'), ('Partially Received', 'Partially Received'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='status', default='Draft', max_length=25)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_created', to=settings.AUTH_USER_MODEL)),
                ('payment_terms', models.ForeignKey(blank=True, db_column='payment_terms', null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.paymentterm')),
                ('supplier_id', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.supplier')),
                ('warehouse_id', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition_number', models.CharField(blank=True, db_column='requisition_number', max_length=50, unique=True)),
                ('created_date', models.DateField(db_column='created_date', default=django.utils.timezone.now)),
                ('department', models.CharField(blank=True, db_column='department', default='', max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Converted', 'Converted to PO')], db_column='status', default='Draft', max_length=20)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_column='approval_status', default='Pending', max_length=20)),
                ('requested_by', models.ForeignKey(blank=True, db_column='requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_requisitions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(db_column='price', decimal_places=4, max_digits=14)),
                ('currency', models.CharField(db_column='currency', default='PKR', max_length=10)),
                ('valid_from', models.DateField(db_column='valid_from')),
                ('valid_to', models.DateField(blank=True, db_column='valid_to', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('supplier_id', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.supplier')),
            ],
            options={
                'db_table': 'supplier_price_history',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq_date', models.DateField(db_column='rfq_date', default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent to Supplier'), ('Received', 'Quotation Received'), ('Closed', 'Closed')], db_column='status', default='Draft', max_length=20)),
                ('requisition_id', models.ForeignKey(blank=True, db_column='requisition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.purchaserequisition')),
                ('supplier_id', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.supplier')),
            ],
            options={
                'db_table': 'request_for_quotations',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(db_column='batch_number', max_length=100, unique=True)),
                ('supplier_batch', models.CharField(blank=True, db_column='supplier_batch', default='', max_length=100)),
                ('manufacture_date', models.DateField(blank=True, db_column='manufacture_date', null=True)),
                ('expiry_date', models.DateField(blank=True, db_column='expiry_date', null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Hold', 'On Hold')], db_column='status', default='Hold', max_length=20)),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
            ],
            options={
                'db_table': 'raw_material_batches',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quoted_price', models.DecimalField(db_column='quoted_price', decimal_places=4, max_digits=14)),
                ('currency', models.CharField(db_column='currency', default='PKR', max_length=10)),
                ('delivery_days', models.IntegerField(db_column='delivery_days', default=7)),
                ('valid_until', models.DateField(blank=True, db_column='valid_until', null=True)),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('rfq_id', models.ForeignKey(db_column='rfq_id', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.requestforquotation')),
                ('supplier_id', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.supplier')),
            ],
            options={
                'db_table': 'quotations',
            },
        ),
        migrations.CreateModel(
            name='QcInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_date', models.DateField(db_column='inspection_date', default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Conditional', 'Conditional')], db_column='result', max_length=20)),
                ('remarks', models.TextField(blank=True, db_column='remarks', default='')),
                ('batch_id', models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.rawmaterialbatch')),
                ('grn_id', models.ForeignKey(blank=True, db_column='grn_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.goodsreceipt')),
                ('inspector', models.ForeignKey(blank=True, db_column='inspector', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
            ],
            options={
                'db_table': 'qc_inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=3, max_digits=14)),
                ('reason', models.TextField(db_column='reason')),
                ('return_date', models.DateField(db_column='return_date', default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='status', default='Draft', max_length=20)),
                ('grn_id', models.ForeignKey(blank=True, db_column='grn_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.goodsreceipt')),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
            ],
            options={
                'db_table': 'purchase_returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_quantity', models.DecimalField(db_column='requested_quantity', decimal_places=3, max_digits=14)),
                ('required_date', models.DateField(blank=True, db_column='required_date', null=True)),
                ('remarks', models.TextField(blank=True, db_column='remarks', default='')),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('requisition_id', models.ForeignKey(db_column='requisition_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequisition')),
                ('warehouse_id', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'purchase_requisition_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_quantity', models.DecimalField(db_column='ordered_quantity', decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(db_column='unit_price', decimal_places=4, max_digits=14)),
                ('tax_rate', models.DecimalField(db_column='tax_rate', decimal_places=2, default=0, max_digits=5)),
                ('discount', models.DecimalField(db_column='discount', decimal_places=2, default=0, max_digits=5)),
                ('total_price', models.DecimalField(db_column='total_price', decimal_places=2, default=0, max_digits=15)),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('po_id', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_qty', models.DecimalField(db_column='ordered_qty', decimal_places=3, default=0, max_digits=14)),
                ('received_qty', models.DecimalField(db_column='received_qty', decimal_places=3, max_digits=14)),
                ('accepted_qty', models.DecimalField(db_column='accepted_qty', decimal_places=3, default=0, max_digits=14)),
                ('rejected_qty', models.DecimalField(db_column='rejected_qty', decimal_places=3, default=0, max_digits=14)),
                ('batch_number', models.CharField(blank=True, db_column='batch_number', default='', max_length=100)),
                ('bin_id', models.ForeignKey(blank=True, db_column='bin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.warehousebin')),
                ('grn_id', models.ForeignKey(db_column='grn_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.goodsreceipt')),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
            ],
            options={
                'db_table': 'goods_receipt_items',
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='po_id',
            field=models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, db_column='received_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier_id',
            field=models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse_id',
            field=models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse'),
        ),
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_column='invoice_number', max_length=100)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=15)),
                ('due_date', models.DateField(blank=True, db_column='due_date', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], db_column='status', default='Pending', max_length=20)),
                ('po_id', models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.purchaseorder')),
                ('supplier_id', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.supplier')),
            ],
            options={
                'db_table': 'accounts_payable',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_material_code', models.CharField(blank=True, db_column='supplier_material_code', default='', max_length=100)),
                ('lead_time_days', models.IntegerField(db_column='lead_time_days', default=7)),
                ('minimum_order_qty', models.DecimalField(db_column='minimum_order_qty', decimal_places=3, default=0, max_digits=14)),
                ('standard_price', models.DecimalField(db_column='standard_price', decimal_places=4, max_digits=14)),
                ('currency', models.CharField(db_column='currency', default='PKR', max_length=10)),
                ('preferred_supplier', models.BooleanField(db_column='preferred_supplier', default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='status', default='active', max_length=20)),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('supplier_id', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.supplier')),
            ],
            options={
                'db_table': 'supplier_materials',
                'unique_together': {('supplier_id', 'material_id')},
            },
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_stock', models.DecimalField(db_column='minimum_stock', decimal_places=3, max_digits=14)),
                ('maximum_stock', models.DecimalField(db_column='maximum_stock', decimal_places=3, max_digits=14)),
                ('reorder_quantity', models.DecimalField(db_column='reorder_quantity', decimal_places=3, max_digits=14)),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('warehouse_id', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'reorder_rules',
                'unique_together': {('material_id', 'warehouse_id')},
            },
        ),
    ]
