# Generated by Django 4.2.11 on 2026-04-06 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='received_date',
            field=models.DateField(db_column='received_date', default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(db_column='order_date', default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='created_date',
            field=models.DateField(db_column='created_date', default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='rfq_date',
            field=models.DateField(db_column='rfq_date', default=django.utils.timezone.localdate),
        ),
    ]
