# Generated by Django 4.2.11 on 2026-04-06 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_goodsreceipt_received_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='received_date',
            field=models.DateField(db_column='received_date', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(db_column='order_date', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='created_date',
            field=models.DateField(db_column='created_date', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='rfq_date',
            field=models.DateField(db_column='rfq_date', default=datetime.date.today),
        ),
    ]
