# Generated by Django 4.2.11 on 2026-04-06 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_goodsreceipt_received_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_date',
            field=models.DateField(db_column='return_date', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='inspection_date',
            field=models.DateField(db_column='inspection_date', default=datetime.date.today),
        ),
    ]
