# Generated by Django 4.2.11 on 2026-04-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_packagingmaterial'),
        ('procurement', '0004_alter_purchasereturn_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='quantity',
            field=models.DecimalField(db_column='quantity', decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='supplier_id',
            field=models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.supplier'),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.warehouse'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='material_id',
            field=models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.rawmaterial'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', default=''),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='quantity',
            field=models.DecimalField(blank=True, db_column='quantity', decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='required_date',
            field=models.DateField(blank=True, db_column='required_date', null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='rfq_number',
            field=models.CharField(blank=True, db_column='rfq_number', max_length=50, unique=True),
        ),
    ]
