# Generated by Django 4.2.11 on 2026-04-06 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='transfer_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], db_column='status', default='Draft', max_length=50)),
                ('created_date', models.DateField(db_column='created_date', default=datetime.date.today)),
                ('dispatched_date', models.DateField(blank=True, db_column='dispatched_date', null=True)),
                ('received_date', models.DateField(blank=True, db_column='received_date', null=True)),
                ('destination_warehouse', models.ForeignKey(db_column='destination_warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='master_data.warehouse')),
                ('source_warehouse', models.ForeignKey(db_column='source_warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'stock_transfers',
            },
        ),
        migrations.CreateModel(
            name='WarehousePicking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='picking_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(blank=True, db_column='order_id', help_text='Sales Order or Production Order ID', null=True)),
                ('picking_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='picking_status', default='Pending', max_length=50)),
                ('start_time', models.DateTimeField(blank=True, db_column='start_time', null=True)),
                ('end_time', models.DateTimeField(blank=True, db_column='end_time', null=True)),
                ('picker_id', models.ForeignKey(blank=True, db_column='picker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse_id', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'warehouse_picking',
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='transfer_item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, db_column='batch_number', default='', max_length=100)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=4, max_digits=14)),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.product')),
                ('transfer_id', models.ForeignKey(db_column='transfer_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
            ],
            options={
                'db_table': 'transfer_items',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='reservation_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(blank=True, db_column='order_id', help_text='Sales Order or Production Order ID', null=True)),
                ('batch_number', models.CharField(blank=True, db_column='batch_number', default='', max_length=100)),
                ('reserved_quantity', models.DecimalField(db_column='reserved_quantity', decimal_places=4, max_digits=14)),
                ('reservation_status', models.CharField(choices=[('Reserved', 'Reserved'), ('Released', 'Released'), ('Dispatched', 'Dispatched'), ('Cancelled', 'Cancelled')], db_column='reservation_status', default='Reserved', max_length=50)),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.product')),
                ('warehouse_id', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'stock_reservations',
            },
        ),
        migrations.CreateModel(
            name='PickingItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='picking_item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, db_column='batch_number', default='', max_length=100)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=4, max_digits=14)),
                ('bin_id', models.ForeignKey(blank=True, db_column='bin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.warehousebin')),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('picking_id', models.ForeignKey(db_column='picking_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehousepicking')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.product')),
            ],
            options={
                'db_table': 'picking_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='adjustment_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, db_column='batch_number', default='', max_length=100)),
                ('adjustment_type', models.CharField(choices=[('Shrinkage', 'Shrinkage'), ('Found', 'Found'), ('Damaged', 'Damaged'), ('Correction', 'Correction')], db_column='adjustment_type', max_length=50)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=4, help_text='Can be positive or negative depending on context.', max_digits=14)),
                ('reason', models.TextField(db_column='reason')),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.product')),
                ('warehouse_id', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'inventory_adjustments',
            },
        ),
        migrations.CreateModel(
            name='BatchTable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='batch_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_column='batch_number', max_length=100, unique=True)),
                ('production_date', models.DateField(db_column='production_date', default=datetime.date.today)),
                ('expiry_date', models.DateField(blank=True, db_column='expiry_date', null=True)),
                ('status', models.CharField(choices=[('In Production', 'In Production'), ('Quality Hold', 'Quality Hold'), ('Approved', 'Approved'), ('Blocked', 'Blocked'), ('Expired', 'Expired')], db_column='status', default='Quality Hold', max_length=50)),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.product')),
            ],
            options={
                'db_table': 'batch_table',
            },
        ),
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(blank=True, db_column='batch_number', default='', max_length=100)),
                ('total_stock', models.DecimalField(db_column='total_stock', decimal_places=4, default=0, max_digits=14)),
                ('reserved_stock', models.DecimalField(db_column='reserved_stock', decimal_places=4, default=0, max_digits=14)),
                ('available_stock', models.DecimalField(db_column='available_stock', decimal_places=4, default=0, max_digits=14)),
                ('in_transit_stock', models.DecimalField(db_column='in_transit_stock', decimal_places=4, default=0, max_digits=14)),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.product')),
                ('warehouse_id', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'inventory_summary',
                'indexes': [models.Index(fields=['warehouse_id', 'material_id', 'product_id'], name='inventory_s_warehou_2e5250_idx')],
                'unique_together': {('warehouse_id', 'material_id', 'product_id', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='ledger_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('item_type', models.CharField(choices=[('Material', 'Material'), ('Product', 'Product')], db_column='item_type', max_length=50)),
                ('batch_number', models.CharField(blank=True, db_column='batch_number', default='', max_length=100)),
                ('movement_type', models.CharField(choices=[('GRN', 'Goods Receipt Note'), ('DISPATCH', 'Customer Dispatch'), ('TRANSFER', 'Warehouse Transfer'), ('PRODUCTION', 'Production Consumption'), ('ADJUSTMENT', 'Stock Adjustment'), ('RETURN', 'Customer Return'), ('EXPIRED', 'Expired Write-off')], db_column='movement_type', max_length=50)),
                ('quantity_in', models.DecimalField(db_column='quantity_in', decimal_places=4, default=0, max_digits=14)),
                ('quantity_out', models.DecimalField(db_column='quantity_out', decimal_places=4, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(db_column='balance_after', decimal_places=4, default=0, max_digits=14)),
                ('reference_type', models.CharField(blank=True, db_column='reference_type', default='', help_text='e.g. PurchaseOrder, ProductionOrder', max_length=100)),
                ('reference_id', models.UUIDField(blank=True, db_column='reference_id', help_text='Source document UUID', null=True)),
                ('bin_id', models.ForeignKey(blank=True, db_column='bin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.warehousebin')),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.rawmaterial')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.product')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse_id', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'inventory_ledger',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['material_id', 'product_id', 'warehouse_id', 'batch_number'], name='inventory_l_materia_838882_idx'), models.Index(fields=['movement_type', 'timestamp'], name='inventory_l_movemen_4636b0_idx')],
            },
        ),
    ]
