# Generated by Django 4.2.11 on 2026-04-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryledger',
            name='movement_type',
            field=models.CharField(choices=[('GRN', 'Goods Receipt Note'), ('PRODUCTION_ISSUE', 'Production Issue'), ('PRODUCTION_OUTPUT', 'Production Output'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('SALES_DISPATCH', 'Sales Dispatch'), ('SALES_RETURN', 'Sales Return'), ('ADJUSTMENT', 'Stock Adjustment'), ('DAMAGE', 'Damage Write-off'), ('EXPIRY', 'Expiry Write-off')], db_column='movement_type', max_length=50),
        ),
    ]
