# Generated by Django 4.2.11 on 2026-04-15 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_add_vehicle_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='customer_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='customer_name', max_length=255)),
                ('region', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('KP', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('AJK', 'Azad Jammu & Kashmir'), ('GB', 'Gilgit-Baltistan'), ('ICT', 'Islamabad Capital Territory')], db_column='region', max_length=20)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=6, max_digits=9, null=True)),
                ('delivery_priority', models.PositiveSmallIntegerField(db_column='delivery_priority', default=3, help_text='1=Highest, 5=Lowest')),
                ('credit_limit', models.DecimalField(db_column='credit_limit', decimal_places=4, default=0, max_digits=18)),
                ('payment_terms', models.CharField(choices=[('NET7', 'Net 7 Days'), ('NET15', 'Net 15 Days'), ('NET30', 'Net 30 Days'), ('NET60', 'Net 60 Days'), ('COD', 'Cash on Delivery'), ('ADVANCE', 'Advance Payment')], db_column='payment_terms', default='NET30', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_column='status', default='active', max_length=20)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='order_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_source', models.CharField(choices=[('sales_app', 'Sales App'), ('manual_entry', 'Manual Entry'), ('distributor_portal', 'Distributor Portal')], db_column='order_source', default='manual_entry', max_length=30)),
                ('order_number', models.CharField(db_column='order_number', max_length=50, unique=True)),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now)),
                ('order_status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Approved', 'Approved'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], db_column='order_status', default='Draft', max_length=20)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Cheque', 'Cheque'), ('Online', 'Online Transfer')], db_column='payment_type', default='Credit', max_length=20)),
                ('total_amount', models.DecimalField(db_column='total_amount', decimal_places=4, default=0, max_digits=20)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.customer')),
                ('warehouse_id', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'sales_orders',
                'ordering': ['-order_date', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='return_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_date', models.DateField(db_column='return_date', default=django.utils.timezone.now)),
                ('return_reason', models.TextField(db_column='return_reason')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], db_column='status', default='Requested', max_length=20)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='sales.customer')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='return_item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, db_column='batch_number', default='', max_length=100)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=4, default=0, max_digits=14)),
                ('condition', models.CharField(choices=[('Resellable', 'Resellable'), ('Damaged', 'Damaged'), ('Expired', 'Expired')], db_column='condition', default='Resellable', max_length=20)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='master_data.product')),
                ('return_id', models.ForeignKey(db_column='return_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn')),
            ],
            options={
                'db_table': 'sales_return_items',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='order_item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=4, default=0, max_digits=14)),
                ('unit_price', models.DecimalField(db_column='unit_price', decimal_places=4, default=0, max_digits=14)),
                ('discount', models.DecimalField(db_column='discount', decimal_places=2, default=0, help_text='Discount percentage (0–100)', max_digits=6)),
                ('tax', models.DecimalField(db_column='tax', decimal_places=2, default=0, help_text='Tax percentage (0–100)', max_digits=6)),
                ('total_price', models.DecimalField(db_column='total_price', decimal_places=4, default=0, max_digits=18)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='master_data.product')),
            ],
            options={
                'db_table': 'sales_order_items',
            },
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='dispatch_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(db_column='driver_name', max_length=150)),
                ('dispatch_date', models.DateField(db_column='dispatch_date', default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Returned', 'Returned')], db_column='status', default='Pending', max_length=20)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_orders', to='sales.salesorder')),
                ('vehicle_id', models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_orders', to='master_data.vehicle')),
                ('warehouse_id', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_orders', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'dispatch_orders',
                'ordering': ['-dispatch_date'],
            },
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='dispatch_item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, db_column='batch_number', default='', max_length=100)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=4, default=0, max_digits=14)),
                ('dispatch_id', models.ForeignKey(db_column='dispatch_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.dispatchorder')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='master_data.product')),
            ],
            options={
                'db_table': 'dispatch_items',
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='delivery_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivered_by', models.CharField(db_column='delivered_by', max_length=150)),
                ('delivery_time', models.DateTimeField(db_column='delivery_time', default=django.utils.timezone.now)),
                ('customer_signature', models.TextField(blank=True, db_column='customer_signature', default='', help_text='Base64 image or signature reference')),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Partially', 'Partially Delivered'), ('Rejected', 'Rejected')], db_column='status', default='Delivered', max_length=20)),
                ('dispatch_id', models.OneToOneField(db_column='dispatch_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmation', to='sales.dispatchorder')),
            ],
            options={
                'db_table': 'delivery_confirmations',
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='credit_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_column='transaction_date', default=django.utils.timezone.now)),
                ('entry_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Payment', 'Payment'), ('Credit Note', 'Credit Note'), ('Adjustment', 'Adjustment')], db_column='entry_type', default='Invoice', max_length=20)),
                ('invoice_amount', models.DecimalField(db_column='invoice_amount', decimal_places=4, default=0, help_text='Positive = amount billed / owed', max_digits=20)),
                ('payment_received', models.DecimalField(db_column='payment_received', decimal_places=4, default=0, help_text='Positive = amount paid', max_digits=20)),
                ('balance', models.DecimalField(db_column='balance', decimal_places=4, default=0, help_text='Running outstanding balance after this entry', max_digits=20)),
                ('reference_id', models.UUIDField(blank=True, db_column='reference_id', help_text='UUID of the SalesOrder or SalesReturn that generated this entry', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='sales.customer')),
            ],
            options={
                'db_table': 'customer_credit_ledger',
                'ordering': ['customer_id', 'transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['region'], name='customers_region_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='customers_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['delivery_priority'], name='customers_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['return_id'], name='sri_return_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['product_id'], name='sri_product_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['order_id'], name='sr_order_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['customer_id'], name='sr_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['status'], name='sr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['order_id'], name='soi_order_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['product_id'], name='soi_product_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer_id', 'order_date'], name='so_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_status'], name='so_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_number'], name='so_number_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['order_id'], name='do_order_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['status'], name='do_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchitem',
            index=models.Index(fields=['dispatch_id'], name='di_dispatch_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryconfirmation',
            index=models.Index(fields=['dispatch_id'], name='dc_dispatch_idx'),
        ),
        migrations.AddIndex(
            model_name='customercreditledger',
            index=models.Index(fields=['customer_id', 'transaction_date'], name='ccl_customer_date_idx'),
        ),
    ]
