# Generated by Django 4.2.11 on 2026-04-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, db_column='address', default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, db_column='contact_person', default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('modern_trade', 'Modern Trade'), ('institutional', 'Institutional')], db_column='customer_type', default='retailer', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_column='email', default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', default='', max_length=50),
        ),
    ]
