# Generated by Django 4.2.11 on 2026-04-06 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('planned_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'production_orders',
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Display / execution order', unique=True)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0, help_text='Expected time for this stage in minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'production_stages',
                'ordering': ['sequence'],
            },
        ),
    ]
