# Generated by Django 4.2.11 on 2026-04-14 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='production_batch_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_column='batch_number', help_text='Must match inventory.BatchTable.batch_number', max_length=100, unique=True)),
                ('planned_quantity', models.DecimalField(db_column='planned_quantity', decimal_places=4, default=0, max_digits=14)),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('On Hold', 'On Hold')], db_column='status', default='In Progress', max_length=20)),
                ('notes', models.TextField(blank=True, db_column='notes', default='')),
                ('operator_id', models.ForeignKey(blank=True, db_column='operator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='master_data.product')),
                ('production_line_id', models.ForeignKey(blank=True, db_column='production_line_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.productionline')),
                ('production_order_id', models.ForeignKey(blank=True, db_column='production_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='manufacturing.productionorder')),
            ],
            options={
                'db_table': 'production_batches',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='productionstage',
            options={'ordering': ['sequence_number']},
        ),
        migrations.RenameField(
            model_name='productionstage',
            old_name='sequence',
            new_name='sequence_number',
        ),
        migrations.CreateModel(
            name='ProductionYield',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='yield_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_quantity', models.DecimalField(db_column='planned_quantity', decimal_places=4, default=0, max_digits=14)),
                ('actual_quantity', models.DecimalField(db_column='actual_quantity', decimal_places=4, default=0, max_digits=14)),
                ('waste_quantity', models.DecimalField(db_column='waste_quantity', decimal_places=4, default=0, max_digits=14)),
                ('yield_percentage', models.DecimalField(db_column='yield_percentage', decimal_places=2, default=0, help_text='actual / planned × 100', max_digits=6)),
                ('unit_of_measure', models.CharField(blank=True, db_column='unit_of_measure', default='', max_length=50)),
                ('recorded_at', models.DateTimeField(blank=True, db_column='recorded_at', null=True)),
                ('qc_approved', models.BooleanField(db_column='qc_approved', default=False)),
                ('notes', models.TextField(blank=True, db_column='notes', default='')),
                ('batch_id', models.OneToOneField(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='yield_record', to='manufacturing.productionbatch')),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_yields',
            },
        ),
        migrations.CreateModel(
            name='OilConsumptionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='oil_log_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oil_type', models.CharField(choices=[('Palm', 'Palm Oil'), ('Sunflower', 'Sunflower Oil'), ('Canola', 'Canola Oil'), ('Blended', 'Blended Oil'), ('Other', 'Other')], db_column='oil_type', default='Palm', max_length=50)),
                ('opening_reading', models.DecimalField(db_column='opening_reading', decimal_places=4, default=0, help_text='Tank level or meter reading at batch start', max_digits=12)),
                ('closing_reading', models.DecimalField(db_column='closing_reading', decimal_places=4, default=0, help_text='Tank level or meter reading at batch end', max_digits=12)),
                ('consumed', models.DecimalField(db_column='consumed', decimal_places=4, default=0, help_text='Auto-computed: opening − closing', max_digits=12)),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure', default='kg', max_length=20)),
                ('unit_cost', models.DecimalField(db_column='unit_cost', decimal_places=4, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(db_column='total_cost', decimal_places=4, default=0, max_digits=16)),
                ('logged_at', models.DateTimeField(blank=True, db_column='logged_at', null=True)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='oil_logs', to='manufacturing.productionbatch')),
                ('logged_by', models.ForeignKey(blank=True, db_column='logged_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', help_text='Oil raw-material master record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.rawmaterial')),
            ],
            options={
                'db_table': 'oil_consumption_logs',
                'ordering': ['logged_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='material_issue_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_quantity', models.DecimalField(db_column='issued_quantity', decimal_places=4, max_digits=14)),
                ('unit_of_measure', models.CharField(blank=True, db_column='unit_of_measure', default='', max_length=50)),
                ('unit_cost', models.DecimalField(db_column='unit_cost', decimal_places=4, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(db_column='total_cost', decimal_places=4, default=0, max_digits=16)),
                ('issued_at', models.DateTimeField(blank=True, db_column='issued_at', null=True)),
                ('raw_material_batch', models.CharField(blank=True, db_column='raw_material_batch', default='', help_text='Supplier lot / batch number of the raw material', max_length=100)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='material_issues', to='manufacturing.productionbatch')),
                ('issued_by', models.ForeignKey(blank=True, db_column='issued_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues', to=settings.AUTH_USER_MODEL)),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='material_issues', to='master_data.rawmaterial')),
                ('supplier_id', models.ForeignKey(blank=True, db_column='supplier_id', help_text='Actual supplier from whom this material was sourced for this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.supplier')),
            ],
            options={
                'db_table': 'material_issues',
                'ordering': ['issued_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchStageLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='stage_log_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Skipped', 'Skipped'), ('Failed', 'Failed')], db_column='status', default='Pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, db_column='start_time', null=True)),
                ('end_time', models.DateTimeField(blank=True, db_column='end_time', null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, db_column='temperature_celsius', decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.TextField(blank=True, db_column='remarks', default='')),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='manufacturing.productionbatch')),
                ('machine_id', models.ForeignKey(blank=True, db_column='machine_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.machine')),
                ('operator_id', models.ForeignKey(blank=True, db_column='operator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_logs', to=settings.AUTH_USER_MODEL)),
                ('stage_id', models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.CASCADE, related_name='batch_logs', to='manufacturing.productionstage')),
            ],
            options={
                'db_table': 'batch_stage_logs',
                'ordering': ['stage_id__sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='BatchCostSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='cost_summary_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_cost', models.DecimalField(db_column='material_cost', decimal_places=4, default=0, max_digits=16)),
                ('oil_cost', models.DecimalField(db_column='oil_cost', decimal_places=4, default=0, max_digits=16)),
                ('labour_cost', models.DecimalField(db_column='labour_cost', decimal_places=4, default=0, max_digits=16)),
                ('overhead_cost', models.DecimalField(db_column='overhead_cost', decimal_places=4, default=0, max_digits=16)),
                ('packaging_cost', models.DecimalField(db_column='packaging_cost', decimal_places=4, default=0, max_digits=16)),
                ('total_cost', models.DecimalField(db_column='total_cost', decimal_places=4, default=0, max_digits=18)),
                ('cost_per_unit', models.DecimalField(db_column='cost_per_unit', decimal_places=4, default=0, max_digits=14)),
                ('currency', models.CharField(db_column='currency', default='PKR', max_length=10)),
                ('calculated_at', models.DateTimeField(blank=True, db_column='calculated_at', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', default='')),
                ('batch_id', models.OneToOneField(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='cost_summary', to='manufacturing.productionbatch')),
                ('calculated_by', models.ForeignKey(blank=True, db_column='calculated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_cost_summaries',
            },
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['batch_number'], name='production__batch_n_e3235b_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['product_id', 'status'], name='production__product_cb7569_idx'),
        ),
        migrations.AddIndex(
            model_name='oilconsumptionlog',
            index=models.Index(fields=['batch_id'], name='oil_consump_batch_i_b6b86c_idx'),
        ),
        migrations.AddIndex(
            model_name='materialissue',
            index=models.Index(fields=['batch_id', 'material_id'], name='material_is_batch_i_e5c2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstagelog',
            index=models.Index(fields=['batch_id', 'stage_id'], name='batch_stage_batch_i_21c24a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchstagelog',
            unique_together={('batch_id', 'stage_id')},
        ),
    ]
