# Generated by Django 4.2.11 on 2026-04-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_exact_schema_adjustments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batchstagelog',
            new_name='batch_stage_batch_i_21c24a_idx',
            old_name='mfg_bsl_batch_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='machinelog',
            new_name='machine_log_machine_7b21a3_idx',
            old_name='mfg_ml_machine_batch_idx',
        ),
        migrations.RenameIndex(
            model_name='materialconsumption',
            new_name='material_co_batch_i_e85526_idx',
            old_name='mfg_mc_batch_material_idx',
        ),
        migrations.RenameIndex(
            model_name='materialissue',
            new_name='material_is_batch_i_e5c2f0_idx',
            old_name='mfg_mi_batch_material_idx',
        ),
        migrations.RenameIndex(
            model_name='materialreservation',
            new_name='material_re_batch_i_d273da_idx',
            old_name='mfg_mr_batch_material_idx',
        ),
        migrations.RenameIndex(
            model_name='oilconsumptionlog',
            new_name='oil_consump_batch_i_b6b86c_idx',
            old_name='mfg_ocl_batch_idx',
        ),
        migrations.RenameIndex(
            model_name='packinglog',
            new_name='packing_log_batch_i_2a4e50_idx',
            old_name='mfg_pl_batch_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatch',
            new_name='production__batch_n_e3235b_idx',
            old_name='mfg_pb_batch_number_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatch',
            new_name='production__product_cb7569_idx',
            old_name='mfg_pb_product_status_idx',
        ),
        migrations.RenameIndex(
            model_name='productionorder',
            new_name='production__status_758765_idx',
            old_name='mfg_po_status_start_idx',
        ),
        migrations.RenameIndex(
            model_name='productionoutput',
            new_name='production__batch_i_459f73_idx',
            old_name='mfg_po_batch_quality_idx',
        ),
        migrations.RenameIndex(
            model_name='productionwaste',
            new_name='production__batch_i_665a17_idx',
            old_name='mfg_pw_batch_type_idx',
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='currency',
            field=models.CharField(default='PKR', max_length=10),
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='labour_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='material_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='oil_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='packaging_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='batchcostsummary',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='batchstagelog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchstagelog',
            name='input_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='batchstagelog',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='batchstagelog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchstagelog',
            name='waste_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='downtime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='downtime_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='runtime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialconsumption',
            name='actual_quantity_used',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='quantity_issued',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='materialreservation',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='materialreservation',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='oilconsumptionlog',
            name='quantity_added',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='oilconsumptionlog',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='packinglog',
            name='packing_machine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packinglog',
            name='packs_produced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packinglog',
            name='rejected_packs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='batch_number',
            field=models.CharField(help_text='Auto: PN{YYMMDD}{A-Z}', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='planned_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(help_text='Auto: PR-YYYY-NNNN', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='planned_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Released', 'Released'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorderitem',
            name='planned_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productionorderitem',
            name='produced_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productionoutput',
            name='batch_number',
            field=models.CharField(help_text='Inventory batch number for traceability', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionoutput',
            name='quality_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionoutput',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='productionwaste',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productionwaste',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productionwaste',
            name='waste_type',
            field=models.CharField(choices=[('Frying Loss', 'Frying Loss'), ('Burnt', 'Burnt'), ('Spillage', 'Spillage'), ('Packing Rejection', 'Packing Rejection')], max_length=50),
        ),
    ]
