# Generated by Django 4.2.11 on 2026-05-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_rename_mfg_bsl_batch_stage_idx_batch_stage_batch_i_21c24a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionyield',
            name='batch_id',
            field=models.OneToOneField(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='yield_records', to='manufacturing.productionbatch'),
        ),
    ]
