# Generated by Django 4.2.11 on 2026-04-06 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRPRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('horizon_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'mrp_runs',
            },
        ),
        migrations.CreateModel(
            name='SeasonalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='e.g. 1.35 means 35% uplift in demand during this season', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'seasonal_configs',
            },
        ),
    ]
