# Generated by Django 4.2.11 on 2026-04-17 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_packagingmaterial'),
        ('mrp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRPPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_id', models.UUIDField(db_column='plan_id', default=uuid.uuid4, editable=False, unique=True)),
                ('forecast_qty', models.DecimalField(db_column='forecast_qty', decimal_places=4, default=0, max_digits=14)),
                ('current_inventory', models.DecimalField(db_column='current_inventory', decimal_places=4, default=0, max_digits=14)),
                ('safety_stock', models.DecimalField(db_column='safety_stock', decimal_places=4, default=0, max_digits=14)),
                ('scheduled_production', models.DecimalField(db_column='scheduled_production', decimal_places=4, default=0, max_digits=14)),
                ('required_production', models.DecimalField(db_column='required_production', decimal_places=4, default=0, max_digits=14)),
                ('planned_production_date', models.DateField(db_column='planned_production_date')),
                ('mrp_run', models.ForeignKey(blank=True, db_column='mrp_run_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='mrp.mrprun')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='mrp_plans', to='master_data.product')),
            ],
            options={
                'db_table': 'mrp_plans',
                'ordering': ['planned_production_date'],
            },
        ),
    ]
