# Generated by Django 4.2.11 on 2026-04-06 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_name', models.CharField(db_column='line_name', max_length=255)),
                ('factory_id', models.UUIDField(db_column='factory_id', help_text='UUID of the Factory warehouse this line belongs to')),
                ('line_type', models.CharField(choices=[('Frying', 'Frying'), ('Mixing', 'Mixing'), ('Extruder', 'Extruder'), ('Packing', 'Packing')], db_column='line_type', max_length=50)),
                ('capacity_per_hour', models.DecimalField(db_column='capacity_per_hour', decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], db_column='status', default='active', max_length=20)),
            ],
            options={
                'db_table': 'production_lines',
                'ordering': ['line_name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_code', models.CharField(db_column='material_code', max_length=100, unique=True)),
                ('material_name', models.CharField(db_column='material_name', max_length=255)),
                ('material_type', models.CharField(choices=[('ingredient', 'Ingredient'), ('oil', 'Oil'), ('spice', 'Spice'), ('packaging', 'Packaging'), ('additive', 'Additive')], db_column='material_type', max_length=50)),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure', max_length=50)),
                ('density', models.DecimalField(blank=True, db_column='density', decimal_places=4, max_digits=10, null=True)),
                ('standard_cost', models.DecimalField(db_column='standard_cost', decimal_places=4, max_digits=14)),
                ('safety_stock', models.DecimalField(db_column='safety_stock', decimal_places=4, default=0, max_digits=14)),
                ('reorder_level', models.DecimalField(db_column='reorder_level', decimal_places=4, default=0, max_digits=14)),
                ('shelf_life_days', models.IntegerField(blank=True, db_column='shelf_life_days', null=True)),
            ],
            options={
                'db_table': 'raw_materials',
                'ordering': ['material_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(db_column='supplier_name', max_length=255)),
                ('contact_person', models.CharField(blank=True, db_column='contact_person', default='', max_length=150)),
                ('phone', models.CharField(blank=True, db_column='phone', default='', max_length=50)),
                ('email', models.EmailField(blank=True, db_column='email', default='', max_length=254)),
                ('payment_terms', models.CharField(blank=True, choices=[('NET30', 'Net 30 Days'), ('NET60', 'Net 60 Days'), ('COD', 'Cash on Delivery'), ('ADVANCE', 'Advance Payment')], db_column='payment_terms', default='NET30', max_length=50)),
                ('currency', models.CharField(db_column='currency', default='PKR', max_length=10)),
                ('lead_time_days', models.IntegerField(db_column='lead_time_days', default=7)),
                ('rating', models.IntegerField(blank=True, db_column='rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_name', models.CharField(db_column='warehouse_name', max_length=255)),
                ('warehouse_type', models.CharField(choices=[('Factory', 'Factory'), ('Regional', 'Regional'), ('City', 'City'), ('Retail', 'Retail')], db_column='warehouse_type', max_length=50)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('province', models.CharField(db_column='province', max_length=100)),
                ('country', models.CharField(db_column='country', default='Pakistan', max_length=100)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='status', default='active', max_length=20)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['warehouse_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(db_column='category_name', max_length=255)),
                ('parent_category', models.ForeignKey(blank=True, db_column='parent_category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='master_data.productcategory')),
            ],
            options={
                'db_table': 'product_category',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_name', models.CharField(db_column='machine_name', max_length=255)),
                ('machine_type', models.CharField(db_column='machine_type', max_length=100)),
                ('capacity_per_hour', models.DecimalField(blank=True, db_column='capacity_per_hour', decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], db_column='status', default='active', max_length=20)),
                ('production_line_id', models.ForeignKey(blank=True, db_column='production_line_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='master_data.productionline')),
            ],
            options={
                'db_table': 'machines',
                'ordering': ['machine_name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseBin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin_code', models.CharField(db_column='bin_code', max_length=50)),
                ('capacity', models.DecimalField(db_column='capacity', decimal_places=3, max_digits=12)),
                ('bin_type', models.CharField(choices=[('Standard', 'Standard'), ('Cold', 'Cold Storage'), ('Hazmat', 'Hazardous Materials'), ('Overflow', 'Overflow')], db_column='bin_type', default='Standard', max_length=50)),
                ('warehouse_id', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'warehouse_bins',
                'unique_together': {('warehouse_id', 'bin_code')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku_code', models.CharField(db_column='sku_code', max_length=100, unique=True)),
                ('product_name', models.CharField(db_column='product_name', max_length=255)),
                ('brand', models.CharField(blank=True, db_column='brand', default='', max_length=100)),
                ('pack_size', models.CharField(db_column='pack_size', max_length=50)),
                ('net_weight', models.DecimalField(db_column='net_weight', decimal_places=3, max_digits=10)),
                ('gross_weight', models.DecimalField(db_column='gross_weight', decimal_places=3, max_digits=10)),
                ('barcode', models.CharField(db_column='barcode', max_length=100, unique=True)),
                ('shelf_life_days', models.IntegerField(db_column='shelf_life_days')),
                ('standard_cost', models.DecimalField(db_column='standard_cost', decimal_places=4, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='status', default='active', max_length=20)),
                ('category_id', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='master_data.productcategory')),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['sku_code'], name='products_sku_cod_167e06_idx'), models.Index(fields=['barcode'], name='products_barcode_d008ac_idx'), models.Index(fields=['category_id'], name='products_categor_4083ff_idx')],
            },
        ),
    ]
