# Generated by Django 4.2.11 on 2026-04-15 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(db_column='registration_number', max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Truck', 'Truck'), ('Mini Truck', 'Mini Truck'), ('Van', 'Van'), ('Motorcycle', 'Motorcycle'), ('Rikshaw', 'Rikshaw')], db_column='vehicle_type', default='Truck', max_length=30)),
                ('capacity_kg', models.DecimalField(db_column='capacity_kg', decimal_places=2, default=0, help_text='Max load capacity in kilograms', max_digits=10)),
                ('driver_name', models.CharField(blank=True, db_column='driver_name', default='', max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], db_column='status', default='active', max_length=20)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['registration_number'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(db_column='selling_price', decimal_places=4, default=0, help_text='Retail / distributor selling price used for SKU profitability', max_digits=14),
        ),
    ]
