# Generated by Django 4.2.11 on 2026-04-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_add_vehicle_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='status', default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='status', default='active', max_length=20),
        ),
    ]
