# Generated by Django 4.2.11 on 2026-04-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_rawmaterial_status_supplier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(db_column='material_type', max_length=50),
        ),
    ]
