# Generated by Django 4.2.11 on 2026-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_alter_rawmaterial_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='current_stock',
            field=models.DecimalField(db_column='current_stock', decimal_places=4, default=0, max_digits=14),
        ),
    ]
