# Generated by Django 4.2.11 on 2026-04-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_rawmaterial_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, db_column='address', default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, db_column='city', default='', max_length=100),
        ),
    ]
