# Generated by Django 4.2.11 on 2026-04-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_supplier_address_supplier_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplied_materials',
            field=models.ManyToManyField(blank=True, db_table='supplier_materials_mapping', related_name='suppliers', to='master_data.rawmaterial'),
        ),
    ]
