# Generated by Django 4.2.11 on 2026-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_supplier_supplied_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='factory_id',
            field=models.UUIDField(blank=True, db_column='factory_id', help_text='UUID of the Factory warehouse this line belongs to', null=True),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='line_type',
            field=models.CharField(db_column='line_type', help_text='Comma separated processes or main type', max_length=255),
        ),
    ]
