# Generated by Django 4.2.11 on 2026-04-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_alter_productionline_factory_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='factory_id',
        ),
        migrations.AddField(
            model_name='productionline',
            name='factory',
            field=models.ForeignKey(blank=True, db_column='factory_id', help_text='The Factory warehouse this line belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lines', to='master_data.warehouse'),
        ),
    ]
