# Generated by Django 4.2.11 on 2026-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_remove_productionline_factory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='cost_per_hour',
            field=models.DecimalField(db_column='cost_per_hour', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='machine',
            name='depreciation',
            field=models.DecimalField(db_column='depreciation', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenance_cost',
            field=models.DecimalField(db_column='maintenance_cost', decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
