# Generated by Django 4.2.11 on 2026-04-17 04:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_machine_cost_per_hour_machine_depreciation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_code', models.CharField(db_column='material_code', max_length=100, unique=True)),
                ('material_name', models.CharField(db_column='material_name', max_length=255)),
                ('material_type', models.CharField(choices=[('primary', 'Primary Packaging'), ('secondary', 'Secondary Packaging'), ('tertiary', 'Tertiary Packaging')], db_column='material_type', max_length=50)),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure', max_length=50)),
                ('standard_cost', models.DecimalField(db_column='standard_cost', decimal_places=4, max_digits=14)),
                ('safety_stock', models.DecimalField(db_column='safety_stock', decimal_places=4, default=0, max_digits=14)),
                ('reorder_level', models.DecimalField(db_column='reorder_level', decimal_places=4, default=0, max_digits=14)),
                ('current_stock', models.DecimalField(db_column='current_stock', decimal_places=4, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='status', default='active', max_length=20)),
                ('supplier', models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_materials', to='master_data.supplier')),
            ],
            options={
                'db_table': 'packaging_materials',
                'ordering': ['material_name'],
            },
        ),
    ]
