/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('products').del();
  
  // Inserts seed entries for Pakasian Foods products
  await knex('products').insert([
    {
      id: 1,
      name: 'Protein Nimko 100g',
      sku: 'PKF-PN-100G-001',
      barcode: '1234567890123',
      description: 'Premium protein-rich nimko snack with mixed nuts and spices, 100g packet',
      category: 'Snacks',
      brand: 'Pakasian Foods',
      unit: 'pkt',
      cost_price: 25.00,
      selling_price: 35.00,
      min_stock_level: 50.00,
      max_stock_level: 500.00,
      weight: 100.000,
      weight_unit: 'g',
      length: 20.0,
      width: 15.0,
      height: 3.0,
      dimension_unit: 'cm',
      batch_number: 'PKF-PN-100G-2024-001',
      expiry_date: '2025-06-15',
      supplier_name: 'Pakasian Foods Ltd',
      unit_of_measure_id: 1, // Grams
      product_category: 'snacks',
      flavor: 'mixed',
      packaging_type: 'bag',
      net_weight: 100.000,
      gross_weight: 105.000,
      nutrition_info: 'Protein: 15g, Carbs: 45g, Fat: 25g per 100g',
      ingredients: 'Mixed nuts, chickpea flour, spices, salt, oil, preservatives',
      allergen_info: 'Contains nuts, gluten',
      storage_conditions: 'Store in cool, dry place',
      origin_country: 'Pakistan',
      manufacturing_date: '2024-01-15',
      is_perishable: true,
      requires_cold_storage: false,
      shelf_life_days: 365,
      attributes: JSON.stringify({
        'protein_content': '15g per 100g',
        'spice_level': 'medium',
        'nut_mix': 'almonds, cashews, peanuts',
        'packaging_material': 'foil bag',
        'certification': 'HALAL'
      }),
      image_url: '/images/products/protein-nimko-100g.jpg',
      is_active: true,
      is_taxable: true,
      tax_rate: 17.00,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 2,
      name: 'Protein Nimko 250g',
      sku: 'PKF-PN-250G-002',
      barcode: '1234567890124',
      description: 'Premium protein-rich nimko snack with mixed nuts and spices, 250g family pack',
      category: 'Snacks',
      brand: 'Pakasian Foods',
      unit: 'pkt',
      cost_price: 55.00,
      selling_price: 75.00,
      min_stock_level: 30.00,
      max_stock_level: 300.00,
      weight: 250.000,
      weight_unit: 'g',
      length: 25.0,
      width: 18.0,
      height: 4.0,
      dimension_unit: 'cm',
      batch_number: 'PKF-PN-250G-2024-001',
      expiry_date: '2025-06-15',
      supplier_name: 'Pakasian Foods Ltd',
      unit_of_measure_id: 1, // Grams
      product_category: 'snacks',
      flavor: 'mixed',
      packaging_type: 'bag',
      net_weight: 250.000,
      gross_weight: 260.000,
      nutrition_info: 'Protein: 15g, Carbs: 45g, Fat: 25g per 100g',
      ingredients: 'Mixed nuts, chickpea flour, spices, salt, oil, preservatives',
      allergen_info: 'Contains nuts, gluten',
      storage_conditions: 'Store in cool, dry place',
      origin_country: 'Pakistan',
      manufacturing_date: '2024-01-15',
      is_perishable: true,
      requires_cold_storage: false,
      shelf_life_days: 365,
      attributes: JSON.stringify({
        'protein_content': '15g per 100g',
        'spice_level': 'medium',
        'nut_mix': 'almonds, cashews, peanuts',
        'packaging_material': 'foil bag',
        'certification': 'HALAL',
        'family_pack': true
      }),
      image_url: '/images/products/protein-nimko-250g.jpg',
      is_active: true,
      is_taxable: true,
      tax_rate: 17.00,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 3,
      name: 'Spicy Nimko Mix',
      sku: 'PKF-SNM-150G-003',
      barcode: '1234567890125',
      description: 'Spicy mixed nimko with extra chili and traditional Pakistani spices, 150g packet',
      category: 'Snacks',
      brand: 'Pakasian Foods',
      unit: 'pkt',
      cost_price: 30.00,
      selling_price: 42.00,
      min_stock_level: 40.00,
      max_stock_level: 400.00,
      weight: 150.000,
      weight_unit: 'g',
      length: 22.0,
      width: 16.0,
      height: 3.5,
      dimension_unit: 'cm',
      batch_number: 'PKF-SNM-150G-2024-001',
      expiry_date: '2025-05-20',
      supplier_name: 'Pakasian Foods Ltd',
      unit_of_measure_id: 1, // Grams
      product_category: 'snacks',
      flavor: 'spicy',
      packaging_type: 'bag',
      net_weight: 150.000,
      gross_weight: 158.000,
      nutrition_info: 'Protein: 12g, Carbs: 50g, Fat: 22g per 100g',
      ingredients: 'Mixed nuts, chickpea flour, red chili, spices, salt, oil, preservatives',
      allergen_info: 'Contains nuts, gluten, chili',
      storage_conditions: 'Store in cool, dry place',
      origin_country: 'Pakistan',
      manufacturing_date: '2024-01-20',
      is_perishable: true,
      requires_cold_storage: false,
      shelf_life_days: 300,
      attributes: JSON.stringify({
        'spice_level': 'high',
        'chili_content': 'extra',
        'traditional_spices': 'garam masala, cumin, coriander',
        'packaging_material': 'foil bag',
        'certification': 'HALAL',
        'heat_level': '5/5'
      }),
      image_url: '/images/products/spicy-nimko-mix.jpg',
      is_active: true,
      is_taxable: true,
      tax_rate: 17.00,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 4,
      name: 'Salted Chips 50g',
      sku: 'PKF-SC-50G-004',
      barcode: '1234567890126',
      description: 'Crispy salted potato chips with traditional Pakistani seasoning, 50g packet',
      category: 'Snacks',
      brand: 'Pakasian Foods',
      unit: 'pkt',
      cost_price: 15.00,
      selling_price: 22.00,
      min_stock_level: 100.00,
      max_stock_level: 1000.00,
      weight: 50.000,
      weight_unit: 'g',
      length: 18.0,
      width: 12.0,
      height: 2.5,
      dimension_unit: 'cm',
      batch_number: 'PKF-SC-50G-2024-001',
      expiry_date: '2024-12-31',
      supplier_name: 'Pakasian Foods Ltd',
      unit_of_measure_id: 1, // Grams
      product_category: 'snacks',
      flavor: 'salted',
      packaging_type: 'bag',
      net_weight: 50.000,
      gross_weight: 52.000,
      nutrition_info: 'Protein: 3g, Carbs: 35g, Fat: 15g per 100g',
      ingredients: 'Potatoes, palm oil, salt, spices, preservatives',
      allergen_info: 'May contain traces of nuts',
      storage_conditions: 'Store in cool, dry place',
      origin_country: 'Pakistan',
      manufacturing_date: '2024-01-10',
      is_perishable: true,
      requires_cold_storage: false,
      shelf_life_days: 180,
      attributes: JSON.stringify({
        'potato_type': 'local',
        'oil_type': 'palm oil',
        'seasoning': 'traditional Pakistani',
        'packaging_material': 'foil bag',
        'certification': 'HALAL',
        'crispiness': 'extra crispy'
      }),
      image_url: '/images/products/salted-chips-50g.jpg',
      is_active: true,
      is_taxable: true,
      tax_rate: 17.00,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 5,
      name: 'Salted Chips 100g',
      sku: 'PKF-SC-100G-005',
      barcode: '1234567890127',
      description: 'Crispy salted potato chips with traditional Pakistani seasoning, 100g family pack',
      category: 'Snacks',
      brand: 'Pakasian Foods',
      unit: 'pkt',
      cost_price: 28.00,
      selling_price: 40.00,
      min_stock_level: 50.00,
      max_stock_level: 500.00,
      weight: 100.000,
      weight_unit: 'g',
      length: 22.0,
      width: 15.0,
      height: 3.0,
      dimension_unit: 'cm',
      batch_number: 'PKF-SC-100G-2024-001',
      expiry_date: '2024-12-31',
      supplier_name: 'Pakasian Foods Ltd',
      unit_of_measure_id: 1, // Grams
      product_category: 'snacks',
      flavor: 'salted',
      packaging_type: 'bag',
      net_weight: 100.000,
      gross_weight: 105.000,
      nutrition_info: 'Protein: 3g, Carbs: 35g, Fat: 15g per 100g',
      ingredients: 'Potatoes, palm oil, salt, spices, preservatives',
      allergen_info: 'May contain traces of nuts',
      storage_conditions: 'Store in cool, dry place',
      origin_country: 'Pakistan',
      manufacturing_date: '2024-01-10',
      is_perishable: true,
      requires_cold_storage: false,
      shelf_life_days: 180,
      attributes: JSON.stringify({
        'potato_type': 'local',
        'oil_type': 'palm oil',
        'seasoning': 'traditional Pakistani',
        'packaging_material': 'foil bag',
        'certification': 'HALAL',
        'crispiness': 'extra crispy',
        'family_pack': true
      }),
      image_url: '/images/products/salted-chips-100g.jpg',
      is_active: true,
      is_taxable: true,
      tax_rate: 17.00,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    }
  ]);
};
