# Generated by Django 4.2.11 on 2026-04-15 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0005_rename_mfg_bsl_batch_stage_idx_batch_stage_batch_i_21c24a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryOverhead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='overhead_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('overhead_type', models.CharField(blank=True, default='', help_text='e.g. Rent, Depreciation, Insurance', max_length=50)),
                ('monthly_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'factory_overheads',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='factory_ove_is_acti_8f4128_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchCostSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='batch_cost_summary_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('labour_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('machine_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('overhead_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('waste_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_batch_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.OneToOneField(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='costing_summary', to='manufacturing.productionbatch')),
                ('calculated_by', models.ForeignKey(blank=True, db_column='calculated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_cost_summary',
            },
        ),
        migrations.CreateModel(
            name='UnitCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='unit_cost_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_batch_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('quantity_produced', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('cost_date', models.DateField(default=django.utils.timezone.now)),
                ('batch_id', models.OneToOneField(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='unit_cost', to='manufacturing.productionbatch')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='unit_costs', to='master_data.product')),
            ],
            options={
                'db_table': 'unit_costs',
                'indexes': [models.Index(fields=['product_id', 'cost_date'], name='unit_costs_product_74ee5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SKUProfitability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='sku_profitability_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('batches_counted', models.PositiveIntegerField(default=0)),
                ('total_units_produced', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_production_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('avg_unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('gross_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('gross_margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='sku_profitability', to='master_data.product')),
            ],
            options={
                'db_table': 'sku_profitability',
                'ordering': ['-period_start', 'product_id'],
                'indexes': [models.Index(fields=['product_id', 'period_start'], name='sku_profita_product_a26e51_idx')],
                'unique_together': {('product_id', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='MachineCostRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='machine_rate_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_per_hour', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('machine_id', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.CASCADE, related_name='cost_rates', to='master_data.machine')),
            ],
            options={
                'db_table': 'machine_cost_rates',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['machine_id', 'effective_from'], name='machine_cos_machine_91736c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabourLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='labour_log_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_count', models.PositiveSmallIntegerField(default=1)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('shift_date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='labour_logs', to='manufacturing.productionbatch')),
                ('stage_id', models.ForeignKey(blank=True, db_column='stage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_logs', to='manufacturing.productionstage')),
            ],
            options={
                'db_table': 'labour_logs',
                'ordering': ['shift_date'],
                'indexes': [models.Index(fields=['batch_id', 'shift_date'], name='labour_logs_batch_i_ae4898_idx')],
            },
        ),
        migrations.CreateModel(
            name='CostVariance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='cost_variance_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('standard_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=4, default=0, help_text='actual_cost − standard_cost', max_digits=14)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='cost_variances', to='manufacturing.productionbatch')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_variances', to='master_data.product')),
            ],
            options={
                'db_table': 'cost_variances',
                'indexes': [models.Index(fields=['batch_id'], name='cost_varian_batch_i_03723d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchWasteCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='batch_waste_cost_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waste_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='waste_costs', to='manufacturing.productionbatch')),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_waste_costs', to='master_data.rawmaterial')),
            ],
            options={
                'db_table': 'batch_waste_cost',
                'indexes': [models.Index(fields=['batch_id'], name='batch_waste_batch_i_5c9a17_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchOverheadCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='batch_overhead_cost_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='overhead_costs', to='manufacturing.productionbatch')),
                ('overhead_id', models.ForeignKey(db_column='overhead_id', on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='costing.factoryoverhead')),
            ],
            options={
                'db_table': 'batch_overhead_cost',
                'indexes': [models.Index(fields=['batch_id', 'overhead_id'], name='batch_overh_batch_i_ae1527_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchMaterialCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='batch_material_cost_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='material_costs', to='manufacturing.productionbatch')),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='batch_material_costs', to='master_data.rawmaterial')),
            ],
            options={
                'db_table': 'batch_material_cost',
                'indexes': [models.Index(fields=['batch_id', 'material_id'], name='batch_mater_batch_i_2dfe4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchMachineCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='batch_machine_cost_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runtime_hours', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='machine_costs', to='manufacturing.productionbatch')),
                ('machine_id', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.CASCADE, related_name='batch_machine_costs', to='master_data.machine')),
            ],
            options={
                'db_table': 'batch_machine_cost',
                'indexes': [models.Index(fields=['batch_id', 'machine_id'], name='batch_machi_batch_i_f28707_idx')],
            },
        ),
    ]
